# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import calculator_pb2 as calculator__pb2


class CalculateStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Add = channel.unary_unary(
        '/calculator.Calculate/Add',
        request_serializer=calculator__pb2.IntRequest.SerializeToString,
        response_deserializer=calculator__pb2.IntResponse.FromString,
        )
    self.Mul = channel.unary_unary(
        '/calculator.Calculate/Mul',
        request_serializer=calculator__pb2.IntRequest.SerializeToString,
        response_deserializer=calculator__pb2.IntResponse.FromString,
        )
    self.Pow = channel.unary_unary(
        '/calculator.Calculate/Pow',
        request_serializer=calculator__pb2.IntRequest.SerializeToString,
        response_deserializer=calculator__pb2.IntResponse.FromString,
        )


class CalculateServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Mul(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Pow(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculateServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=calculator__pb2.IntRequest.FromString,
          response_serializer=calculator__pb2.IntResponse.SerializeToString,
      ),
      'Mul': grpc.unary_unary_rpc_method_handler(
          servicer.Mul,
          request_deserializer=calculator__pb2.IntRequest.FromString,
          response_serializer=calculator__pb2.IntResponse.SerializeToString,
      ),
      'Pow': grpc.unary_unary_rpc_method_handler(
          servicer.Pow,
          request_deserializer=calculator__pb2.IntRequest.FromString,
          response_serializer=calculator__pb2.IntResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'calculator.Calculate', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
