# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/calculator.proto',
  package='calculator',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16proto/calculator.proto\x12\ncalculator\"\"\n\nIntRequest\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x1d\n\x0bIntResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\xba\x01\n\nCalculator\x12\x38\n\x03\x41\x64\x64\x12\x16.calculator.IntRequest\x1a\x17.calculator.IntResponse\"\x00\x12\x38\n\x03Mul\x12\x16.calculator.IntRequest\x1a\x17.calculator.IntResponse\"\x00\x12\x38\n\x03Pow\x12\x16.calculator.IntRequest\x1a\x17.calculator.IntResponse\"\x00\x62\x06proto3')
)




_INTREQUEST = _descriptor.Descriptor(
  name='IntRequest',
  full_name='calculator.IntRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='calculator.IntRequest.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='calculator.IntRequest.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=72,
)


_INTRESPONSE = _descriptor.Descriptor(
  name='IntResponse',
  full_name='calculator.IntResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='calculator.IntResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['IntRequest'] = _INTREQUEST
DESCRIPTOR.message_types_by_name['IntResponse'] = _INTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntRequest = _reflection.GeneratedProtocolMessageType('IntRequest', (_message.Message,), dict(
  DESCRIPTOR = _INTREQUEST,
  __module__ = 'proto.calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.IntRequest)
  ))
_sym_db.RegisterMessage(IntRequest)

IntResponse = _reflection.GeneratedProtocolMessageType('IntResponse', (_message.Message,), dict(
  DESCRIPTOR = _INTRESPONSE,
  __module__ = 'proto.calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.IntResponse)
  ))
_sym_db.RegisterMessage(IntResponse)



_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='calculator.Calculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=106,
  serialized_end=292,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='calculator.Calculator.Add',
    index=0,
    containing_service=None,
    input_type=_INTREQUEST,
    output_type=_INTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Mul',
    full_name='calculator.Calculator.Mul',
    index=1,
    containing_service=None,
    input_type=_INTREQUEST,
    output_type=_INTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Pow',
    full_name='calculator.Calculator.Pow',
    index=2,
    containing_service=None,
    input_type=_INTREQUEST,
    output_type=_INTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
